import { ExifParserFactory } from 'ts-exif-parser';
import * as fs from 'fs';
import {
  Card,
  Flex,
  List,
  ListItem,
  Metric,
  Subtitle,
  Title
} from '@tremor/react';
import Image from 'next/image';

function convertExposureTimeToFraction(exposureTime: number): string {
  if (exposureTime > 1) {
    return `${exposureTime}"`;
  }
  const denominator = 1 / exposureTime;
  return `1/${Math.round(denominator)}`;
}

function flashTriggered(value: string): string {
  return value !== '0' ? 'Not Triggered' : 'Triggered';
}

export const metadata = {
  title: 'Photo Summary',
  description: 'Generated by create next app'
};

export default function PhotoPage() {
  const data = fs.readFileSync(process.cwd() + '/app/photo/' + 'DSC_9977.jpeg');
  const Data = ExifParserFactory.create(data).parse();
  return (
    <main
      style={{
        backgroundImage: 'url(/karina.jpeg)',
        backgroundSize: 'contain',
        backgroundRepeat: 'no-repeat'
      }}
    >
      <Card className="bg-transparent">
        <Title>Photo Summary</Title>
        <Flex justifyContent={'evenly'}>
          <div className="w-full p-3  border-gray-200 rounded-lg shadow hover:bg-gray-100 text-center">
            <Image
              src="/exposure.png"
              alt="Exposure Time"
              width={24}
              height={24}
              className="mx-auto"
            />
            <Metric>
              {convertExposureTimeToFraction(Data.tags?.ExposureTime!)}
            </Metric>
          </div>
          <div className="w-full p-3   border-gray-200 rounded-lg shadow hover:bg-gray-100 text-center">
            <Image
              src="/aperture.png"
              alt="Make"
              width={24}
              height={24}
              className="mx-auto"
            />
            <Metric>{Data.tags?.FNumber}</Metric>
          </div>
          <div className="w-full p-3 border-gray-200 rounded-lg shadow hover:bg-gray-100 text-center">
            <Image
              src="/iso.png"
              alt="Software"
              width={24}
              height={24}
              className="mx-auto"
            />
            <Metric>{Data.tags?.ISO} </Metric>
          </div>
        </Flex>
        <List className="mt-4">
          <ListItem>
            <Image
              src="/photographer.png"
              alt="Photographer"
              width={24}
              height={24}
            />
            {Data.tags?.Artist}
          </ListItem>
          <ListItem>
            <Image src="/dslr.png" alt="Make" width={24} height={24} />
            {Data.tags?.Model}{' '}
          </ListItem>
          <ListItem>
            <Image src="/camera-lens.png" alt="Make" width={24} height={24} />
            {Data.tags?.LensModel}
          </ListItem>
          <ListItem>
            <Image src="/computer.png" alt="Software" width={24} height={24} />
            {Data.tags?.Software}
          </ListItem>
          <ListItem>
            <Image src="/media.png" alt="Make" width={24} height={24} />
            Available light
          </ListItem>
          <ListItem>
            <Image src="/flash.png" alt="Make" width={24} height={24} />
            {flashTriggered(Data.tags?.Flash!)}
          </ListItem>
        </List>
      </Card>
      <Card className="bg-transparent">
        <Title>
          <Title>Extra Info</Title>
          <List>
            <ListItem>
              <Image src="/makeover.png" alt="MUA" width={24} height={24} />
              Makeup Artist
            </ListItem>
            <ListItem>
              <Image src="/photo.png" alt="Retoucher" width={24} height={24} />
              Retoucher
            </ListItem>
            <ListItem>
              <Image src="/ask.png" alt="Assistant" width={24} height={24} />
              Assistant
            </ListItem>
          </List>
        </Title>
      </Card>
      <Card className="my-2 bg-transparent">
        <Subtitle>Attribution</Subtitle>
        <small>
          <a
            href="https://www.flaticon.com/free-icons/camera-lens"
            title="camera lens icons"
          >
            Camera lens icons created by iconfield - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/photography"
            title="photography icons"
          >
            Photography icons created by Smashicons - Flaticon
          </a>
          <a href="https://www.flaticon.com/free-icons/dslr" title="dslr icons">
            Dslr icons created by Smashicons - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/lighting"
            title="lighting icons"
          >
            Lighting icons created by Smashicons - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/camera-lens"
            title="camera lens icons"
          >
            Camera lens icons created by DinosoftLabs - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/journalist"
            title="journalist icons"
          >
            Journalist icons created by Freepik - Flaticon
          </a>
          <a href="https://www.flaticon.com/free-icons/cms" title="cms icons">
            Cms icons created by Freepik - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/exposure"
            title="exposure icons"
          >
            Exposure icons created by Creatype - Flaticon
          </a>
          <a href="https://www.flaticon.com/free-icons/iso" title="iso icons">
            Iso icons created by Freepik - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/flashlight"
            title="flashlight icons"
          >
            Flashlight icons created by Freepik - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/makeup"
            title="makeup icons"
          >
            Makeup icons created by Freepik - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/retouching"
            title="retouching icons"
          >
            Retouching icons created by Freepik - Flaticon
          </a>
          <a
            href="https://www.flaticon.com/free-icons/raise"
            title="raise icons"
          >
            Raise icons created by Flat Icons Design - Flaticon
          </a>
        </small>
      </Card>
    </main>
  );
}
